name: ESLint Check

on:
  workflow_dispatch:
  push:
    paths:
      - "ts/cluster-comment-service/**.ts"
      - "ts/cluster-comment-service/**.tsx"
      - "ts/cluster-comment-service/package.json"
      - "ts/cluster-comment-service/package-lock.json"
      - "ts/cluster-comment-service/eslint.config.js"
  pull_request:
    paths:
      - "ts/cluster-comment-service/**.ts"
      - "ts/cluster-comment-service/**.tsx"
      - "ts/cluster-comment-service/package.json"
      - "ts/cluster-comment-service/package-lock.json"
      - "ts/cluster-comment-service/eslint.config.js"

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: ts/cluster-comment-service

      - name: Run ESLint
        run: npm run lint
        working-directory: ts/cluster-comment-service
